spring:
  application:
    name: company-service
  profiles:
    active: dev
    
server:
  port: 8081
  servlet:
    context-path: /company
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: ${MONGODB_DEV_URL}

---
spring:
  profiles: prod
  data:
    mongodb:
      uri: ${MONGODB_URL}
  